services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pimcore\Bundle\DataHubBundle\Controller\Studio\:
        resource: '../../Controller/Studio'
        public: true
        tags: [ 'controller.service_arguments' ]