services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Pimcore\Bundle\DataHubBundle\Webpack\WebpackEntryPointProvider:
    tags:
      - { name: 'pimcore_studio_ui.webpack_entry_point_provider' }

