services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pimcore\Bundle\DataHubBundle\Service\Studio\ConfigurationServiceInterface:
        class: Pimcore\Bundle\DataHubBundle\Service\Studio\ConfigurationService

    Pimcore\Bundle\DataHubBundle\Service\Studio\GraphQLExplorerServiceInterface:
        class: Pimcore\Bundle\DataHubBundle\Service\Studio\GraphQLExplorerService

    Pimcore\Bundle\DataHubBundle\Service\Studio\UserServiceInterface:
        class: Pimcore\Bundle\DataHubBundle\Service\Studio\UserService

    Pimcore\Bundle\DataHubBundle\Hydrator\ConfigurationHydratorInterface:
        class: Pimcore\Bundle\DataHubBundle\Hydrator\ConfigurationHydrator

    Pimcore\Bundle\DataHubBundle\Hydrator\ConfigurationDetailHydratorInterface:
        class: Pimcore\Bundle\DataHubBundle\Hydrator\ConfigurationDetailHydrator

    Pimcore\Bundle\DataHubBundle\Hydrator\ConfigurationDehydratorInterface:
        class: Pimcore\Bundle\DataHubBundle\Hydrator\ConfigurationDehydrator

    Pimcore\Bundle\DataHubBundle\Hydrator\PermissionUserHydratorInterface:
        class: Pimcore\Bundle\DataHubBundle\Hydrator\PermissionUserHydrator

    Pimcore\Bundle\DataHubBundle\Service\Studio\ThumbnailServiceInterface:
        class: Pimcore\Bundle\DataHubBundle\Service\Studio\ThumbnailService

    Pimcore\Bundle\DataHubBundle\Hydrator\ThumbnailHydratorInterface:
        class: Pimcore\Bundle\DataHubBundle\Hydrator\ThumbnailHydrator

    #
    # Event Subscriber
    #

    Pimcore\Bundle\DataHubBundle\EventSubscriber\StudioContextPermissionsSubscriber: ~
