<?php
declare(strict_types=1);
/**
 * Pimcore
 *
 * This source file is available under two different licenses:
 * - GNU General Public License version 3 (GPLv3)
 * - Pimcore Enterprise License (PEL)
 * Full copyright and license information is available in
 * LICENSE.md which is distributed with this source code.
 *
 * @copyright  Copyright (c) Pimcore GmbH (http://www.pimcore.org)
 * @license    http://www.pimcore.org/license     GPLv3 and PEL
 */

namespace Pimcore\Bundle\DataHubBundle\GraphQL\OperatorConfigGenerator;

/**
 * Class ThumbnailHtml
 * @package Pimcore\Bundle\DataHubBundle\GraphQL\OperatorConfigGenerator
 */
class ThumbnailHtml extends StringBase
{
    /**
     * @param $config
     * @param null $container
     * @return mixed
     */
    public function enrichConfig($config, $container = null)
    {
        $config['description'] = "A thumbnail HTML snippet which contains the entire image tag as generated by Pimcore";
        return parent::enrichConfig($config, $container);
    }
}
