pimcore_data_hub_studio:
    resource: "@PimcoreDataHubBundle/Controller/Studio"
    type: attribute
    prefix: '%pimcore_studio_backend.url_prefix%/bundle/data-hub'
    options:
        expose: true

admin_pimcoredatahub_webservice:
    path: /pimcore-graphql-webservices/{clientname}
    defaults: { _controller: Pimcore\Bundle\DataHubBundle\Controller\WebserviceController::webonyxAction }

