api_platform:
    resource: api
    type: api_platform
    prefix: /api-platform-webservices

app:
    resource: "@PimcoreDataHubBundle/Controller/"
    type:     annotation


admin_pimcoredatahub_config:
    path: /pimcore-datahub-webservices/explorer/{clientname}
    defaults: { _controller: PimcoreDataHubBundle:GraphQLExplorer:explorer }

admin_pimcoredatahub_webservice:
    path: /pimcore-graphql-webservices/{clientname}
    defaults: { _controller: PimcoreDataHubBundle:Webservice:webonyx }
