name: Frontend build and publish

on:
  push:
    branches:
      - "[0-9]+.x"
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  id-token: write  # Required for OIDC
  contents: write

jobs:
  publish:
    uses: pimcore/workflows-collection-public/.github/workflows/reusable-frontend-publish-unified.yaml@reusable-workflows
    with:
      working-directory: "assets/studio"
      node-version: "24"
      target-release: "2.4.0"
      build-output-path: "./src/Resources/public/studio/"
      pre-publish-script: "generate-types"
    secrets: inherit
