name: "PHP-CS-Fixer"

on:
    pull_request_target:
        branches:
            - "[0-9]+.[0-9]+"
            - "[0-9]+.x"
            - "feature-*"
    push:
        branches:
            - "[0-9]+.[0-9]+"
            - "[0-9]+.x"
            - "*_actions"
            - "feature-*"

permissions:
    contents: read

jobs:
    php-cs-fixer:
        permissions:
            contents: write  # for stefanzweifel/git-auto-commit-action to push code in repo
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.ref }}
                  repository: ${{ github.event.pull_request.head.repo.full_name }}

            - name: PHP-CS-Fixer
              uses: docker://oskarstark/php-cs-fixer-ga:latest

            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: Apply php-cs-fixer changes
